const productos = [
    {
        id: 1,
        nombre:"Batman",
        categoria:"DC",
        precio: 350,
        cantidad: 0,
        descripcion: "figura de accion de Lego",
        img: src="img/lego-batman.png",
    },
    {
        id: 2,
        nombre:"Superman",
        categoria:"DC",
        precio: 400,
        cantidad: 0,
        descripcion: "figura de accion de Lego",
        img:src="img/lego-superman.png",
    },
    {
        id: 3,
        nombre:"Robin",
        categoria:"DC",
        precio: 550,
        cantidad: 0,
        descripcion: "figura de accion de Lego",
        img:src="img/lego-robin.png",
    },
    {
        id: 4,
        nombre:"Iron-Man",
        categoria:"Marvel",
        precio: 600,
        cantidad: 0,
        descripcion: "figura de accion de Lego",
        img:src="img/lego-iron-man.png",
    },
    {
        id: 5,
        nombre:"Hulk",
        categoria:"Marvel",
        precio: 520,
        cantidad: 0,
        descripcion: "figura de accion de Lego",
        img:src="img/lego-hulk.png",
    },
]