const productos = [
    {
        id: 1,
        nombre:"Batman",
        categoria:"DC",
        precio: 500,
        cantidad: 0,
        descripcion: "funko pop",
    },
    {
        id: 2,
        nombre:"Superman",
        categoria:"DC",
        precio: 400,
        cantidad: 0,
        descripcion: "funko pop",
    },
    {
        id: 3,
        nombre:"Robin",
        categoria:"DC",
        precio: 550,
        cantidad: 0,
        descripcion: "funko pop",
    },
    {
        id: 4,
        nombre:"Iron-Man",
        categoria:"Marvel",
        precio: 600,
        cantidad: 0,
        descripcion: "funko pop",
    },
    {
        id: 5,
        nombre:"Hulk",
        categoria:"Marvel",
        precio: 520,
        cantidad: 0,
        descripcion: "funko pop",
    },
]